services:
  - type: web
    name: crafts-project
    runtime: python
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: gunicorn crafts_project.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "*"
