# Generated by Django 5.2.15 on 2026-06-13 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('primary_color', models.CharField(max_length=7)),
                ('primary_hover_color', models.CharField(max_length=7)),
                ('bg_color', models.CharField(max_length=7)),
                ('dark_color', models.CharField(max_length=7)),
                ('primary_light_color', models.CharField(max_length=7)),
                ('border_color', models.CharField(max_length=7)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
