# Generated by Django 5.2.15 on 2026-06-13 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='font_family',
            field=models.CharField(choices=[("'Inter', sans-serif", 'Inter (Clean & Modern)'), ("'Outfit', sans-serif", 'Outfit (Geometric & Premium)'), ("'Cairo', sans-serif", 'Cairo (Perfect Bilingual Arabic/English)'), ("'Playfair Display', serif", 'Playfair (Classic Serif)')], default="'Cairo', sans-serif", max_length=100),
        ),
    ]
