# Generated by Django 5.2.15 on 2026-06-13 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_theme_font_family'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='font_family',
        ),
        migrations.AddField(
            model_name='theme',
            name='font_family_ar',
            field=models.CharField(choices=[("'Cairo', sans-serif", 'Cairo (Modern & Rounded)'), ("'Tajawal', sans-serif", 'Tajawal (Sleek Kufic)'), ("'Almarai', sans-serif", 'Almarai (Corporate Clean)'), ("'Amiri', serif", 'Amiri (Traditional Naskh)')], default="'Cairo', sans-serif", max_length=100),
        ),
        migrations.AddField(
            model_name='theme',
            name='font_family_en',
            field=models.CharField(choices=[("'Inter', sans-serif", 'Inter (Clean & Modern)'), ("'Outfit', sans-serif", 'Outfit (Geometric & Premium)'), ("'Roboto', sans-serif", 'Roboto (Standard Sans)'), ("'Playfair Display', serif", 'Playfair (Classic Serif)')], default="'Inter', sans-serif", max_length=100),
        ),
    ]
