# Generated by Django 5.2.15 on 2026-06-23 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('INSTAPAY', 'Instapay Transfer'), ('COD', 'Cash on Delivery (COD)')], default='INSTAPAY', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='screenshots/'),
        ),
    ]
