# Generated by Django 5.2.15 on 2026-07-03 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_order_payment_method_alter_order_payment_screenshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artisan_promise_title_en', models.CharField(default='Artisan Promise', max_length=200)),
                ('artisan_promise_title_ar', models.CharField(default='عهد الحرفيين', max_length=200)),
                ('artisan_promise_text_en', models.TextField(default='Every product listed is verified 100% handmade and unique.')),
                ('artisan_promise_text_ar', models.TextField(default='كل منتج معروض هنا مضمون أنه مصنوع يدوياً 100% وفريد من نوعه.')),
                ('footer_description_en', models.TextField(default='A premium marketplace dedicated to authentic handcrafts, wooden carvings, rustic pottery, and artisan masterpieces. Bringing human touch back into shopping.')),
                ('footer_description_ar', models.TextField(default='منصة متميزة مخصصة للمشغولات اليدوية الأصيلة، والمنحوتات الخشبية، والفخار الريفي، والقطع الفنية الفريدة. نعيد اللمسة الإنسانية إلى التسوق.')),
                ('free_delivery_title_en', models.CharField(default='Free Delivery', max_length=200)),
                ('free_delivery_title_ar', models.CharField(default='شحن مجاني', max_length=200)),
                ('free_delivery_subtitle_en', models.CharField(default='Orders over EGP 500', max_length=200)),
                ('free_delivery_subtitle_ar', models.CharField(default='للطلبات فوق 500 ج.م', max_length=200)),
                ('secure_checkout_title_en', models.CharField(default='Secure Checkout', max_length=200)),
                ('secure_checkout_title_ar', models.CharField(default='دفع آمن', max_length=200)),
                ('secure_checkout_subtitle_en', models.CharField(default='SSL Secured payments', max_length=200)),
                ('secure_checkout_subtitle_ar', models.CharField(default='مدفوعات مؤمنة بـ SSL', max_length=200)),
                ('empty_cart_title_en', models.CharField(default='Your Cart is Empty', max_length=200)),
                ('empty_cart_title_ar', models.CharField(default='سلة التسوق فارغة', max_length=200)),
                ('empty_cart_text_en', models.TextField(default='Discover authentic wooden carvings, rustic pottery, and hand-woven masterpieces. Add them to your cart to checkout!')),
                ('empty_cart_text_ar', models.TextField(default='اكتشف المنحوتات الخشبية الأصيلة، والفخار الريفي، والتحف المنسوجة يدوياً. أضفها إلى سلتك لإتمام الشراء!')),
                ('founder1_name_en', models.CharField(default='Soffian Elkadi', max_length=200)),
                ('founder1_name_ar', models.CharField(default='سفيان القاضي', max_length=200)),
                ('founder1_role_en', models.CharField(default='Co-Founder & Lead Designer', max_length=200)),
                ('founder1_role_ar', models.CharField(default='شريك مؤسس ومصمم رئيسي', max_length=200)),
                ('founder1_bio_en', models.TextField(default='Soffian is an award-winning ceramicist and digital designer with over a decade of experience styling premium homeware. He steers the visual identity and product quality assurance at Little Creators Shop.')),
                ('founder1_bio_ar', models.TextField(default='سفيان هو خبير فخار ومصمم رقمي حائز على جوائز، يتمتع بخبرة تزيد عن عقد في تصميم الأدوات المنزلية الفاخرة. يقود الهوية البصرية وضمان جودة المنتجات في Little Creators Shop.')),
                ('founder2_name_en', models.CharField(default='Yehia Fatouh', max_length=200)),
                ('founder2_name_ar', models.CharField(default='يحيى فتوح', max_length=200)),
                ('founder2_role_en', models.CharField(default='Co-Founder & Operations Head', max_length=200)),
                ('founder2_role_ar', models.CharField(default='شريك مؤسس ومدير العمليات', max_length=200)),
                ('founder2_bio_en', models.TextField(default='Yehia brings years of supply-chain and logistics management experience in regional craft trade. He supervises our onboarding pipelines, logistics partnerships, and verification guidelines.')),
                ('founder2_bio_ar', models.TextField(default='يحيى يجلب سنوات من الخبرة في إدارة العمليات وسلاسل الإمداد اللوجستية في تجارة الحرف اليدوية الإقليمية. ويشرف على خطوط الإمداد والشراكات اللوجستية وإرشادات التحقق.')),
            ],
        ),
    ]
