# Generated by Django 5.2.15 on 2026-07-03 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_product_rating_product_review_count_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appconfiguration',
            name='artisan_promise_title_en',
            field=models.CharField(default='Discover Handcrafted Masterpieces', max_length=200),
        ),
    ]
