# Generated by Django 5.2.15 on 2026-07-03 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_appconfiguration_artisan_promise_title_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, default=4.5, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='review_count',
            field=models.IntegerField(blank=True, default=12, null=True),
        ),
    ]
